spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${REGION_STATIC}
    stack:
      auto: false
    credentials:
      instance-profile: true
      accessKey: ${AWS_ACCESSKEY}
      secretKey: ${AWS_SECRETKEY}